<a href="https://www.kaggle.com/code/dilekdd/numpy-arrays?scriptVersionId=194474993" target="_blank"><img align="left" alt="Kaggle" title="Open in Kaggle" src="https://kaggle.com/static/images/open-in-kaggle.svg"></a>

Multiply two lists without using numpy arrays

In [1]:
import numpy as np
a = [4, 3, 2, 1]
b = [2, 3, 4, 5]

ab = []

for i in range(0, (len(a))):
    ab.append(a[i] * b[i])
print(ab)

[8, 9, 8, 5]


multiply two numpy arrays

In [2]:
import numpy as np
a = np.array([4, 3, 2, 1])
b = np.array([2, 3, 4, 5])
print(a*b)

[8 9 8 5]


create a Numpy Array

In [3]:
np.array([1, 2, 3, 4, 5])

array([1, 2, 3, 4, 5])

create a Numpy array that consists of 10 zeros and with type INT

In [4]:
np.zeros(10, dtype=int) 

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

create a random array between zero to ten, with the size of 10

In [5]:
np.random.randint(0, 10, size=10)


array([5, 0, 5, 6, 0, 2, 5, 7, 5, 2])

create a normal array with mean=10, s=10, 3 rows, 5 columns

In [6]:
import numpy as np
np.random.normal(10, 4, (3, 4))

array([[ 8.51838649, 11.36649099, 10.15646343, 11.2836754 ],
       [11.6837116 ,  8.21109547,  7.48624359,  6.29773758],
       [16.37612672,  7.11971833, 12.42954016, 10.56604498]])

Create a NumPy array from a list

In [7]:
import numpy as np
lst = [1, 4, 9, 3, 7]
npy_array = np.array(lst)
print(npy_array)

[1 4 9 3 7]


create a 2x3 NumPy array filled with zeros

In [8]:
import numpy as np
npy_array = np.zeros((2, 3))
print(npy_array)

[[0. 0. 0.]
 [0. 0. 0.]]


perform element addition on two NumPy arrays

In [9]:
import numpy as np

array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])
print(array1 + array2)

[5 7 9]


access the element at the 2nd row and 3rd column in a 2D NumPy array

In [10]:
import numpy as np

array_test = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

array_test[1, 2]

6

You have a Numpy array with 1d, 9 random items in the range 1-10. Convert it to random 3d Numpy array

In [11]:
import numpy as np
np.random.randint(1, 10, size=9).reshape(3, 3)

array([[7, 1, 8],
       [4, 5, 4],
       [5, 7, 7]])

In [12]:
import numpy as np
ar = np.random.randint(1, 10, size=9)
ar.reshape(3, 3)


array([[2, 2, 1],
       [1, 8, 1],
       [4, 5, 9]])

Create a Numpy array incrementing by 3 from 0 to 30.

In [13]:
import numpy as np
np.arange(0, 30, 3)

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

you have this array >  array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27]), bring these indices 1, 2, 3

In [14]:
import numpy as np
ar =  np.array([ 0, 3, 6, 9, 12, 15, 18, 21, 24, 27])
catch = [1, 2, 3]
ar[catch]

array([3, 6, 9])